# Generated by Django 4.2.1 on 2023-09-25 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0002_alter_lesson_duration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='access',
            options={'verbose_name': 'Доступ', 'verbose_name_plural': 'Доступы'},
        ),
        migrations.AlterUniqueTogether(
            name='access',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='product',
            name='viewer',
        ),
        migrations.AlterField(
            model_name='access',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_assigment', to='products.product'),
        ),
        migrations.AlterField(
            model_name='access',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_assigment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='products',
            field=models.ManyToManyField(to='products.product', verbose_name='Продукты в которых содержится'),
        ),
    ]
