# Generated by Django 4.2.1 on 2023-09-23 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonViewing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_viewed', models.PositiveIntegerField(default=0, help_text='Продолжительность просмотре видео в секундах', verbose_name='просмотренно (сек)')),
                ('started', models.DateTimeField(auto_now_add=True, verbose_name='дата начала просмотра')),
                ('last_viewed', models.DateTimeField(auto_now=True, verbose_name='дата последнего просмотра')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='related_views', to='products.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='related_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'просмотр урока',
                'verbose_name_plural': 'просмотры уроков',
                'ordering': ('-id',),
            },
        ),
        migrations.AddConstraint(
            model_name='lessonviewing',
            constraint=models.UniqueConstraint(fields=('user', 'lesson'), name='unique_user_lesson_view'),
        ),
    ]
